version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.mysql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [
        "CMD-SHELL", 
        "mysql -uroot -ptest -e 'SELECT 1;' || exit 1"
      ]
      interval: 1s
      timeout: 1s
      retries: 20
      start_period: 5s

  sight:
    build:
      context: .
      dockerfile: Dockerfile.Local
    container_name: sight-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/sight
      # 개발 환경과 도커 환경의 OS가 다르기 때문에 `node_modules`를 공유하지 않습니다.
      - /sight/node_modules
